// <auto-generated />
using System;
using JoseRivera_Ap1_p1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoseRivera_Ap1_p1.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("CobroId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.CobrosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorCobrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleId");

                    b.HasIndex("CobroId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("CobrosDetalle");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Deudores", b =>
                {
                    b.Property<int>("DeudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeudorId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Deudores");

                    b.HasData(
                        new
                        {
                            DeudorId = 1,
                            Nombres = "Jose"
                        },
                        new
                        {
                            DeudorId = 2,
                            Nombres = "Josue"
                        },
                        new
                        {
                            DeudorId = 3,
                            Nombres = "Juan"
                        },
                        new
                        {
                            DeudorId = 4,
                            Nombres = "Verde"
                        },
                        new
                        {
                            DeudorId = 5,
                            Nombres = "Pedro"
                        });
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Balance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("PrestamoId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Cobros", b =>
                {
                    b.HasOne("JoseRivera_Ap1_p1.Models.Deudores", "Deudor")
                        .WithMany("Cobros")
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.CobrosDetalle", b =>
                {
                    b.HasOne("JoseRivera_Ap1_p1.Models.Cobros", "cobros")
                        .WithMany("CobrosDetalle")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseRivera_Ap1_p1.Models.Prestamos", "Prestamos")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamos");

                    b.Navigation("cobros");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Deudores", b =>
                {
                    b.HasOne("JoseRivera_Ap1_p1.Models.Prestamos", null)
                        .WithMany("Deudores")
                        .HasForeignKey("PrestamoId");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Prestamos", b =>
                {
                    b.HasOne("JoseRivera_Ap1_p1.Models.Deudores", "Deudor")
                        .WithMany("Prestamos")
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Cobros", b =>
                {
                    b.Navigation("CobrosDetalle");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Deudores", b =>
                {
                    b.Navigation("Cobros");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("JoseRivera_Ap1_p1.Models.Prestamos", b =>
                {
                    b.Navigation("Deudores");
                });
#pragma warning restore 612, 618
        }
    }
}
